version: "3.2"
volumes:
  couchdb_data: 
  opt:
  var:
  couchdb_log:
  persistence:
  server:
  populateDB:
  media: 
services:
  couchdb:
    build: 
      context: .
      dockerfile: couchbase/Dockerfile
    ports:
      - 5984:5984
    volumes:
      - type: volume
        source: couchdb_data
        target: /opt/couchdb/data
        read_only: False 
    privileged: true
    environment:
        - COUCHDB_HOST
        - COUCHDB_PORT
        - COUCHDB_USERNAME
        - COUCHDB_PASSWORD
        - HOSTEDCOUCH
        - HOSTEDCOUCHPASSWORD
        - HOSTEDCOUCHURL
        - COUCHBASE_ADMINISTRATOR_USERNAME
        - COUCHBASE_ADMINISTRATOR_PASSWORD
        - COUCHBASE_BUCKET
        - COUCHBASE_BUCKET_PASSWORD
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      
    ports:
       - 3000:3000
       - 3001:3001
       - 3002:3003
       - 3333:3333
       - 3334:3334
    volumes:
       - ./server/media:/usr/src/app/server/media
       - ./server:/usr/src/app/server
       - ./populateDB:/usr/src/app/populateDB
       - ./src:/usr/src/app/src
       - ./public:/usr/src/app/public
    environment:
       - APPLICATION_PORT
       - CLIENT_PORT
       - SERVER_PORT
       - SECRET_KEY
       - APP_NAME
       - HOSTEDCOUCH
       - HOSTEDCOUCHPASSWORD
       - HOSTEDCOUCHURL
       - COUCHBASE_ADMINISTRATOR_USERNAME
       - COUCHBASE_ADMINISTRATOR_PASSWORD
       - COUCHBASE_BUCKET
       - COUCHBASE_BUCKET_PASSWORD
       - COUCHBASE_HOST
       - NODE_ENV
       - SKIP_PREFLIGHT_CHECK
       - COUCHDB_USERNAME
       - COUCHDB_PASSWORD

       
