
FROM  frodenas/couchdb
 
COPY configure.sh /opt/couchbase
# ENV MY_HOME "/couchbase"
# WORKDIR $MY_HOME
# RUN /opt/couchbase/configure.sh
# ENTRYPOINT ["sh", "/opt/couchbase/configure.sh"] 
CMD ["/opt/couchbase/configure.sh"]